### ISSUE TITLE
MangaUpdates

### ISSUE THREAD

**Issue by Metaroka** [AtsumeruDev/Atsumeru#4]
On www.mangaupdates.com, the links to the titles have changed

**Comment by AtsumeruDev** [comment]
Fixed in [Atsumeru](https://github.com/AtsumeruDev/Atsumeru/commit/d4938198513dbe1aadc607b6097e79e64a061705) and [Atsumeru API](https://github.com/AtsumeruDev/Atsumeru-API/commit/1a8a7303dfaee1731ccbd7c46e4de3b9f9c749d7)
